### ISSUE TITLE
Validate arguments passed to / from script

### ISSUE THREAD

**Issue by andrey-p** [andrey-p/ectoplasm-js#4]
Because the transport Ectoplasm is using relies on JSON, we can only pass serialisable properties between Node and Phantom. There needs to be some validation logic for that.

**Comment by knownasilya** [comment]
Also would be nice to mention that in the readme.

**Comment by andrey-p** [comment]
@knownasilya Good point - I'm thinking I'll make a note of it in the readme only. Adding an extra check will just add overhead for not much gain.
